### ISSUE TITLE
MASA.DCC Roadmap for 0.70 

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.DCC#210]
### Roadmap

This issue represents a list of major investments that our team will focus on in the 0.7.0 time frame. It doesn't include all the features and bug fixes we'll be working on in the meantime
这个Issue代表我们团队将在 0.7.0 内重点关注的列表。它不包括我们将在此期间进行的所有功能和错误修复。

Note that this is an aspirational list of what we hope to get to. Many of these items will require thorough investigation and design, which can result in changes to our plans. We will end up cutting some things and making changes as we go, but will try to keep this issue up to date to reflect on our progress and learnings.
请注意，这是一个我们希望达到的愿望清单。 其中许多项目需要彻底的调查和设计，这可能会导致我们的计划发生变化。我们最终可能会消减一些东西，并做出改变，但将努力保持这个Issue是最新的，以反映我们的进步和学习。  

The roadmap consists of the following features:
路线图包括以下特性

### Landscape（全景）

**Environment（环境）**

* [x] List（列表）

**Cluster（集群）**

* [x] List（列表）

**Project（项目）**

* [x] List（列表）

**App（应用）**

* [x] List（列表）
* [x] Pin

### Team（团队）

> 以团队视角查看项目和应用，以项目和应用为主体
>
> View projects and applications from a team perspective, focusing on projects and applications

**团队**

- [x] Detail（详情）

**Project（项目）**

* [x] List（列表）
* [x] Search（搜索）

**App（应用）**

* [x] List（列表）
* [x] Search（搜索）

### Label management（标签管理）

- [x] Add（新增）
- [x] Edit（编辑）
- [x] Delete（删除）
- [x] List（列表）
- [x] Detail（详情）
- [x] Search（查询）

### Config（配置）

- [x] Environment cluster list（环境集群列表）
- [x] list（列表）
- [x] Config type support Json、XML、Property、Yaml、Raw（配置类型支持Json、XML、Property、Yaml、Raw）
- [x] Delete（删除）
- [x] Edit（编辑）
- [x] Search（搜索）
- [x] Release（发布）
- [x] Rollback（回滚）
- [x] Release history（发布历史）
- [x] Revoke（撤销）
- [x] Text and property conversion（Text和Property相互转换）
- [x] Config Encryption（配置加密）
- [ ] Secret management（密钥管理）

#### Biz config（业务配置）

- [x] Clone（克隆）

#### App config（应用配置）

- [x] Connect public config（关联公共配置）
- [x] Clone（克隆）

**Comment by doddgu** [comment]
@LazyEar0 PTAL
